### ISSUE TITLE
Docker image support for ARM64 architecture

### ISSUE THREAD

**Issue by rahimrasool** [uchicago-dsi/textbook-datascience-1#53]
I cloned the repo with fresh installation. However, 2 other people are facing the issue below after making a change and then running `manage build` command.

The command does not complete execution. Terminal stays stuck at this message.

```
latest: Pulling from uchicago-dsi/textbook-jupyter-service
Digest: sha256:15832ecaa3c431f67d859aa48fa040f6ec5f68ffdbeb624f79f812282abef908
Status: Image is up to date for ghcr.io/uchicago-dsi/textbook-jupyter-service:latest
ghcr.io/uchicago-dsi/textbook-jupyter-service:latest
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
Running Jupyter-Book v0.13.1
Source Folder: /home/jovyan/textbook
Config Path: /home/jovyan/textbook/_config.yml
Output Path: /home/jovyan/preview/_build/html
```

**Comment by jesteria** [comment]
On what platform(s) is this seen? According to the warning message, these are ARM64 processor computers that are having issues.

Are these all perhaps recent Apple computers with Apple Silicon processors?

We can certainly support that platform; but it is a different architecture, for which the Docker image isn't currently built.

**Comment by rahimrasool** [comment]
Yes, that's what I also figured out as well. I am running this on the M1 Max. The other person who reported is also running it on the Apple M1.
